In [1]:
learning_rate = 0.01
num_steps = 20
batch_size = 20
total_numbers = 291
display_step = 1000
examples_to_show = 10
import tensorflow as tf
# Network Parameters
num_hidden_1 = 64 # 1st layer num features
num_hidden_2 = 16 # 2nd layer num features (the latent dim)
num_input = 27
num_classes = 7

# tf Graph input (only pictures)
X = tf.placeholder("float", [None, num_input])
Y = tf.placeholder("float", [None, num_classes])


weights = {
    'encoder_h1': tf.Variable(tf.random_normal([num_input, num_hidden_1])),
    'encoder_h2': tf.Variable(tf.random_normal([num_hidden_1, num_hidden_2])),
    'decoder_h1': tf.Variable(tf.random_normal([num_hidden_2, num_hidden_1])),
    'decoder_h2': tf.Variable(tf.random_normal([num_hidden_1, num_input])),
    'classifier_h': tf.Variable(tf.random_normal([num_hidden_2, num_classes])),
}
biases = {
    'encoder_b1': tf.Variable(tf.random_normal([num_hidden_1])),
    'encoder_b2': tf.Variable(tf.random_normal([num_hidden_2])),
    'decoder_b1': tf.Variable(tf.random_normal([num_hidden_1])),
    'decoder_b2': tf.Variable(tf.random_normal([num_input])),
    'classifier_b': tf.Variable(tf.random_normal([num_classes])),
}

In [2]:
# Building the encoder
def encoder(x):
    # Encoder Hidden layer with sigmoid activation #1
    layer_1 = tf.nn.sigmoid(tf.add(tf.matmul(x, weights['encoder_h1']),
                                   biases['encoder_b1']))
    # Encoder Hidden layer with sigmoid activation #2
    layer_2 = tf.nn.sigmoid(tf.add(tf.matmul(layer_1, weights['encoder_h2']),
                                   biases['encoder_b2']))
    return layer_2


# Building the decoder
def decoder(x):
    # Decoder Hidden layer with sigmoid activation #1
    layer_1 = tf.nn.sigmoid(tf.add(tf.matmul(x, weights['decoder_h1']),
                                   biases['decoder_b1']))
    # Decoder Hidden layer with sigmoid activation #2
    layer_2 = tf.nn.sigmoid(tf.add(tf.matmul(layer_1, weights['decoder_h2']),
                                   biases['decoder_b2']))
    return layer_2

# Construct model
encoder_op = encoder(X)
decoder_op = decoder(encoder_op)

# Prediction
y_pred = decoder_op

label_pred = tf.nn.softmax(tf.add(tf.matmul(encoder_op, weights['classifier_h']), biases['classifier_b']))
y_clipped = tf.clip_by_value(label_pred, 1e-10, 0.9999999)


# Targets (Labels) are the input data.
y_true = X
label_true = Y

# Define loss and optimizer, minimize the squared error
loss_autoencoder = tf.reduce_mean(tf.pow(y_true - y_pred, 2))
cross_entropy_loss = -tf.reduce_mean(tf.reduce_sum(label_true * tf.log(y_clipped)
                         + (1 - label_true) * tf.log(1 - y_clipped), axis=1))
loss_total = loss_autoencoder+cross_entropy_loss

optimizer = tf.train.RMSPropOptimizer(learning_rate).minimize(loss_total)

# Initialize the variables (i.e. assign their default value)
init = tf.global_variables_initializer()

In [3]:
from numpy import genfromtxt
my_data = genfromtxt('./DataForBiplab/2017Kharif_NDVI1.csv', delimiter=',')
my_data1 = genfromtxt('./DataForBiplab/2017Kharif_VV1.csv', delimiter=',')
my_data0 = genfromtxt('./DataForBiplab/2017Kharif_VH1.csv', delimiter=',')

In [4]:
data = my_data[1:,2:]
data1 = my_data1[1:,2:]
data0 = my_data0[1:,2:]
print(data.shape)
print(data1.shape)
print(data0.shape)

(546, 13)
(546, 14)
(546, 14)


In [5]:
print(data.max())
print(data1.max())
print(data0.max())

0.855952701
3.165250778
0.209239975


In [6]:
import numpy as np
data = np.array(data)
data1 = np.array(data1)
data0 = np.array(data0)
print(data.shape)
print(data1.shape)
print(data0.shape)

(546, 13)
(546, 14)
(546, 14)


In [7]:
import pandas
colnames = ['Latitude', 'Longitude', 'CropType','SampleYear','ShowingPeriod'
           , 'HarvestingPeriod', 'Others']
data3 = pandas.read_csv('./DataForBiplab/FieldDataKharif2017.csv', names=colnames)

In [8]:
ctype = data3.CropType.tolist()
print(ctype)

['CropType', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Paddy', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcane', 'Sugarcan

In [9]:
p = np.array(ctype)
print(p.shape)

(547,)


In [10]:
lbl1 = ctype
label = []
for i in range(1,547):
    if(lbl1[i] == "Paddy"):
        label += [0]
    if(lbl1[i] == "Sugarcane"):
        label += [1]
    if(lbl1[i] == "PearlMillet"):
        label += [2]
    if(lbl1[i] == "PigeonPea"):
        label += [3]
    if(lbl1[i] == "Sorghum"):
        label += [4]
    if(lbl1[i] == "Forest/NonCropland"):
        label += [5]
    if(lbl1[i] == "Habitation"):
        label += [6]
    
print(label)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 

In [11]:
label = np.array(label)
print(label.shape)

(546,)


In [12]:
print(data.shape)
print(data1.shape)
print(data0.shape)
data4=data1/data0
data2 = np.concatenate((data,data4), axis=1)
print(data2.shape)

(546, 13)
(546, 14)
(546, 14)
(546, 27)


In [13]:
x1=[]
x2=[]
x3=[]
x4=[]
x5=[]
x6=[]
x7=[]
l1=[]
l2=[]
l3=[]
l4=[]
l5=[]
l6=[]
l7=[]
for i in range(0, label.shape[0]):
    if(label[i]==0):
        x1.append(data2[i])
        l1.append([1,0,0,0,0,0,0])
    if(label[i]==1):
        x2.append(data2[i])
        l2.append([0,1,0,0,0,0,0])
    if(label[i]==2):
        x3.append(data2[i])
        l3.append([0,0,1,0,0,0,0])
    if(label[i]==3):
        x4.append(data2[i])
        l4.append([0,0,0,1,0,0,0])
    if(label[i]==4):
        x5.append(data2[i])
        l5.append([0,0,0,0,1,0,0])
    if(label[i]==5):
        x6.append(data2[i])
        l6.append([0,0,0,0,0,1,0])
    if(label[i]==6):
        x7.append(data2[i])
        l7.append([0,0,0,0,0,0,1])
x1=np.array(x1)
x2=np.array(x2)
x3=np.array(x3)
x4=np.array(x4)
x5=np.array(x5)
x6=np.array(x6)
x7=np.array(x7)

l1=np.array(l1)
l2=np.array(l2)
l3=np.array(l3)
l4=np.array(l4)
l5=np.array(l5)
l6=np.array(l6)
l7=np.array(l7)

print(l7.shape)
print(x6.shape)

(209, 7)
(34, 27)


In [14]:
from sklearn.utils import shuffle
data2, label = shuffle(data2, label, random_state = 0)

In [15]:
# 80% train 20% test (NDVIclean)
X_train = data2[0:436,:]
X_test = data2[436:,:]
y_train = label[0:436]
y_test = label[436:]

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(436, 27)
(110, 27)
(436,)
(110,)


In [16]:
from keras.utils import np_utils
y_test = np_utils.to_categorical(y_test)
y_train = np_utils.to_categorical(y_train)
print(y_train.shape)
print(y_test.shape)

(436, 7)
(110, 7)


/home/aniruddha/anaconda3/envs/tensorflow/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [17]:
# Start Training
# Start a new TF session
sess = tf.Session()

# Run the initializer
sess.run(init)
batch_size = 20
num_batch = 12

# Training
for i in range(0,1000):
    k = 0 
    # Prepare Data
    # Get the next batch of MNIST data (only images are needed, not labels)
    avg_cost = 0
    for j in (0,num_batch):
        batch_x = X_train[k:k+batch_size,:]
        batch_y = y_train[k:k+batch_size,:]
        k += 29

    # Run optimization op (backprop) and cost op (to get loss value)
        _, l = sess.run([optimizer, loss_total], feed_dict={X: batch_x, Y: batch_y})
        avg_cost += l / num_batch
    print("Epoch:", (i + 1), "cost =", "{:.8f}".format(avg_cost))

Epoch: 1 cost = 2.62348127
Epoch: 2 cost = 2.58867582
Epoch: 3 cost = 2.55654756
Epoch: 4 cost = 2.52421419
Epoch: 5 cost = 2.48945665
Epoch: 6 cost = 2.45065355
Epoch: 7 cost = 2.40671611
Epoch: 8 cost = 2.35760450
Epoch: 9 cost = 2.30498640
Epoch: 10 cost = 2.25189304
Epoch: 11 cost = 2.20176840
Epoch: 12 cost = 2.15682896
Epoch: 13 cost = 2.11708736
Epoch: 14 cost = 2.08393192
Epoch: 15 cost = 2.05749917
Epoch: 16 cost = 2.03580133
Epoch: 17 cost = 2.01726723
Epoch: 18 cost = 2.00064834
Epoch: 19 cost = 1.98469305
Epoch: 20 cost = 1.96827730
Epoch: 21 cost = 1.95035998
Epoch: 22 cost = 1.93008463
Epoch: 23 cost = 1.90718246
Epoch: 24 cost = 1.88179588
Epoch: 25 cost = 1.85413798
Epoch: 26 cost = 1.82559141
Epoch: 27 cost = 1.79849760
Epoch: 28 cost = 1.77395089
Epoch: 29 cost = 1.75097521
Epoch: 30 cost = 1.72814027
Epoch: 31 cost = 1.70671980
Epoch: 32 cost = 1.69034441
Epoch: 33 cost = 1.67827535
Epoch: 34 cost = 1.66721805
Epoch: 35 cost = 1.65529672
Epoch: 36 cost = 1.64077846
E

Epoch: 335 cost = 1.21608659
Epoch: 336 cost = 1.21589732
Epoch: 337 cost = 1.21591747
Epoch: 338 cost = 1.21574247
Epoch: 339 cost = 1.21591620
Epoch: 340 cost = 1.21626687
Epoch: 341 cost = 1.21593030
Epoch: 342 cost = 1.21591775
Epoch: 343 cost = 1.21582778
Epoch: 344 cost = 1.21570019
Epoch: 345 cost = 1.21574950
Epoch: 346 cost = 1.21597652
Epoch: 347 cost = 1.21584980
Epoch: 348 cost = 1.21579218
Epoch: 349 cost = 1.21600699
Epoch: 350 cost = 1.21586323
Epoch: 351 cost = 1.21600993
Epoch: 352 cost = 1.21587284
Epoch: 353 cost = 1.21588361
Epoch: 354 cost = 1.21572542
Epoch: 355 cost = 1.21575181
Epoch: 356 cost = 1.21591091
Epoch: 357 cost = 1.21596217
Epoch: 358 cost = 1.21589077
Epoch: 359 cost = 1.21604753
Epoch: 360 cost = 1.21583847
Epoch: 361 cost = 1.21572220
Epoch: 362 cost = 1.21579134
Epoch: 363 cost = 1.21569264
Epoch: 364 cost = 1.21588111
Epoch: 365 cost = 1.21591234
Epoch: 366 cost = 1.21616411
Epoch: 367 cost = 1.21602607
Epoch: 368 cost = 1.21586804
Epoch: 369 cos

Epoch: 639 cost = 1.21566657
Epoch: 640 cost = 1.21557065
Epoch: 641 cost = 1.21564384
Epoch: 642 cost = 1.21558416
Epoch: 643 cost = 1.21563061
Epoch: 644 cost = 1.21549428
Epoch: 645 cost = 1.21554108
Epoch: 646 cost = 1.21554784
Epoch: 647 cost = 1.21549416
Epoch: 648 cost = 1.21550484
Epoch: 649 cost = 1.21549769
Epoch: 650 cost = 1.21551967
Epoch: 651 cost = 1.21558726
Epoch: 652 cost = 1.21562020
Epoch: 653 cost = 1.21568064
Epoch: 654 cost = 1.21556087
Epoch: 655 cost = 1.21555277
Epoch: 656 cost = 1.21547270
Epoch: 657 cost = 1.21546940
Epoch: 658 cost = 1.21543566
Epoch: 659 cost = 1.21550028
Epoch: 660 cost = 1.21558209
Epoch: 661 cost = 1.21557760
Epoch: 662 cost = 1.21563629
Epoch: 663 cost = 1.21558138
Epoch: 664 cost = 1.21559572
Epoch: 665 cost = 1.21556727
Epoch: 666 cost = 1.21572900
Epoch: 667 cost = 1.21553449
Epoch: 668 cost = 1.21546805
Epoch: 669 cost = 1.21547771
Epoch: 670 cost = 1.21559095
Epoch: 671 cost = 1.21549857
Epoch: 672 cost = 1.21547337
Epoch: 673 cos

Epoch: 944 cost = 1.21549495
Epoch: 945 cost = 1.21545625
Epoch: 946 cost = 1.21545804
Epoch: 947 cost = 1.21542843
Epoch: 948 cost = 1.21543547
Epoch: 949 cost = 1.21545513
Epoch: 950 cost = 1.21545927
Epoch: 951 cost = 1.21552980
Epoch: 952 cost = 1.21550981
Epoch: 953 cost = 1.21546185
Epoch: 954 cost = 1.21551017
Epoch: 955 cost = 1.21545955
Epoch: 956 cost = 1.21545978
Epoch: 957 cost = 1.21542974
Epoch: 958 cost = 1.21547441
Epoch: 959 cost = 1.21548112
Epoch: 960 cost = 1.21541425
Epoch: 961 cost = 1.21536422
Epoch: 962 cost = 1.21550635
Epoch: 963 cost = 1.21550826
Epoch: 964 cost = 1.21551303
Epoch: 965 cost = 1.21553719
Epoch: 966 cost = 1.21551534
Epoch: 967 cost = 1.21550409
Epoch: 968 cost = 1.21541735
Epoch: 969 cost = 1.21545033
Epoch: 970 cost = 1.21541142
Epoch: 971 cost = 1.21538166
Epoch: 972 cost = 1.21546868
Epoch: 973 cost = 1.21549992
Epoch: 974 cost = 1.21548784
Epoch: 975 cost = 1.21556135
Epoch: 976 cost = 1.21548335
Epoch: 977 cost = 1.21540066
Epoch: 978 cos

In [18]:
# define an accuracy assessment operation
correct_prediction = tf.equal(tf.argmax(Y, 1), tf.argmax(label_pred, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [19]:
print(y_test.shape)

(110, 7)


In [20]:
# on 1000 epoch
print(sess.run(accuracy, feed_dict={X: X_test, Y: y_test}))

0.59999996


In [21]:
res1=np.array(sess.run(tf.argmax(label_pred,1), feed_dict={X: x1, Y: l1}))
res2=np.array(sess.run(tf.argmax(label_pred,1), feed_dict={X: x2, Y: l2}))
res3=np.array(sess.run(tf.argmax(label_pred,1), feed_dict={X: x3, Y: l3}))
res4=np.array(sess.run(tf.argmax(label_pred,1), feed_dict={X: x4, Y: l4}))
res5=np.array(sess.run(tf.argmax(label_pred,1), feed_dict={X: x5, Y: l5}))
res6=np.array(sess.run(tf.argmax(label_pred,1), feed_dict={X: x6, Y: l6}))
res7=np.array(sess.run(tf.argmax(label_pred,1), feed_dict={X: x7, Y: l7}))
print(res6)

[5 1 5 6 1 1 1 1 5 1 1 1 1 5 5 5 5 1 5 5 5 6 5 2 2 5 5 5 2 5 5 5 5 5]


In [22]:
confusion=[]
x1=np.sum(np.equal(res1, 0))
x2=np.sum(np.equal(res1, 1))
x3=np.sum(np.equal(res1, 2))
x4=np.sum(np.equal(res1, 3))
x5=np.sum(np.equal(res1, 4))
x6=np.sum(np.equal(res1, 5))
x7=np.sum(np.equal(res1, 6))
confusion.append([x1,x2,x3,x4,x5,x6,x7])

x1=np.sum(np.equal(res2, 0))
x2=np.sum(np.equal(res2, 1))
x3=np.sum(np.equal(res2, 2))
x4=np.sum(np.equal(res2, 3))
x5=np.sum(np.equal(res2, 4))
x6=np.sum(np.equal(res2, 5))
x7=np.sum(np.equal(res2, 6))
confusion.append([x1,x2,x3,x4,x5,x6,x7])

x1=np.sum(np.equal(res3, 0))
x2=np.sum(np.equal(res3, 1))
x3=np.sum(np.equal(res3, 2))
x4=np.sum(np.equal(res3, 3))
x5=np.sum(np.equal(res3, 4))
x6=np.sum(np.equal(res3, 5))
x7=np.sum(np.equal(res3, 6))
confusion.append([x1,x2,x3,x4,x5,x6,x7])

x1=np.sum(np.equal(res4, 0))
x2=np.sum(np.equal(res4, 1))
x3=np.sum(np.equal(res4, 2))
x4=np.sum(np.equal(res4, 3))
x5=np.sum(np.equal(res4, 4))
x6=np.sum(np.equal(res4, 5))
x7=np.sum(np.equal(res4, 6))
confusion.append([x1,x2,x3,x4,x5,x6,x7])

x1=np.sum(np.equal(res5, 0))
x2=np.sum(np.equal(res5, 1))
x3=np.sum(np.equal(res5, 2))
x4=np.sum(np.equal(res5, 3))
x5=np.sum(np.equal(res5, 4))
x6=np.sum(np.equal(res5, 5))
x7=np.sum(np.equal(res5, 6))
confusion.append([x1,x2,x3,x4,x5,x6,x7])

x1=np.sum(np.equal(res6, 0))
x2=np.sum(np.equal(res6, 1))
x3=np.sum(np.equal(res6, 2))
x4=np.sum(np.equal(res6, 3))
x5=np.sum(np.equal(res6, 4))
x6=np.sum(np.equal(res6, 5))
x7=np.sum(np.equal(res6, 6))
confusion.append([x1,x2,x3,x4,x5,x6,x7])

x1=np.sum(np.equal(res7, 0))
x2=np.sum(np.equal(res7, 1))
x3=np.sum(np.equal(res7, 2))
x4=np.sum(np.equal(res7, 3))
x5=np.sum(np.equal(res7, 4))
x6=np.sum(np.equal(res7, 5))
x7=np.sum(np.equal(res7, 6))
confusion.append([x1,x2,x3,x4,x5,x6,x7])

confusion=np.array(confusion)
print(confusion)

[[ 33   5   1   0   9   1  12]
 [  4 115   3   0   7  12  31]
 [  5   2   7   0   6   1  12]
 [  0   8   0   0   0   0   2]
 [  3   4   1   0  10   0   9]
 [  0  10   3   0   0  19   2]
 [  9  25   6   0   5   4 160]]


In [65]:
# 70% train 30% test (NDVIclean)
# Train - 204
# Test - 87
X_train = data2[0:382,:]
X_test = data2[382:,:]
y_train = label[0:382]
y_test = label[382:]

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(382, 27)
(164, 27)
(382,)
(164,)


In [66]:
from keras.utils import np_utils
y_test = np_utils.to_categorical(y_test)
y_train = np_utils.to_categorical(y_train)
print(y_train.shape)
print(y_test.shape)

(382, 7)
(164, 7)


In [71]:
# Start Training
# Start a new TF session
sess = tf.Session()

# Run the initializer
sess.run(init)
batch_size = 20
num_batch = 10

# Training
for i in range(0,1000):
    k = 0 
    # Prepare Data
    # Get the next batch of MNIST data (only images are needed, not labels)
    avg_cost = 0
    for j in (0,num_batch):
        batch_x = X_train[k:k+batch_size,:]
        batch_y = y_train[k:k+batch_size,:]
        k += 29

    # Run optimization op (backprop) and cost op (to get loss value)
        _, l = sess.run([optimizer, loss_total], feed_dict={X: batch_x, Y: batch_y})
        avg_cost += l / num_batch
    print("Epoch:", (i + 1), "cost =", "{:.8f}".format(avg_cost))

Epoch: 1 cost = 2.89531193
Epoch: 2 cost = 2.79956989
Epoch: 3 cost = 2.71618786
Epoch: 4 cost = 2.64462967
Epoch: 5 cost = 2.58379507
Epoch: 6 cost = 2.53224545
Epoch: 7 cost = 2.48848305
Epoch: 8 cost = 2.45122070
Epoch: 9 cost = 2.41954298
Epoch: 10 cost = 2.39267778
Epoch: 11 cost = 2.36963491
Epoch: 12 cost = 2.34943047
Epoch: 13 cost = 2.33131256
Epoch: 14 cost = 2.31472578
Epoch: 15 cost = 2.29926682
Epoch: 16 cost = 2.28466654
Epoch: 17 cost = 2.27074966
Epoch: 18 cost = 2.25734205
Epoch: 19 cost = 2.24421158
Epoch: 20 cost = 2.23113546
Epoch: 21 cost = 2.21807537
Epoch: 22 cost = 2.20521345
Epoch: 23 cost = 2.19261942
Epoch: 24 cost = 2.18020945
Epoch: 25 cost = 2.16806164
Epoch: 26 cost = 2.15635233
Epoch: 27 cost = 2.14519606
Epoch: 28 cost = 2.13453569
Epoch: 29 cost = 2.12411842
Epoch: 30 cost = 2.11359224
Epoch: 31 cost = 2.10247555
Epoch: 32 cost = 2.08981047
Epoch: 33 cost = 2.07359409
Epoch: 34 cost = 2.05159636
Epoch: 35 cost = 2.02550387
Epoch: 36 cost = 2.00074453
E

Epoch: 320 cost = 1.45890145
Epoch: 321 cost = 1.45902362
Epoch: 322 cost = 1.45899520
Epoch: 323 cost = 1.45898614
Epoch: 324 cost = 1.45911970
Epoch: 325 cost = 1.45910816
Epoch: 326 cost = 1.45899310
Epoch: 327 cost = 1.45896740
Epoch: 328 cost = 1.45898943
Epoch: 329 cost = 1.45908585
Epoch: 330 cost = 1.45910935
Epoch: 331 cost = 1.45890708
Epoch: 332 cost = 1.45908008
Epoch: 333 cost = 1.45926313
Epoch: 334 cost = 1.45908222
Epoch: 335 cost = 1.45887146
Epoch: 336 cost = 1.45904527
Epoch: 337 cost = 1.45895953
Epoch: 338 cost = 1.45899315
Epoch: 339 cost = 1.45906310
Epoch: 340 cost = 1.45912404
Epoch: 341 cost = 1.45915465
Epoch: 342 cost = 1.45907836
Epoch: 343 cost = 1.45912099
Epoch: 344 cost = 1.45895853
Epoch: 345 cost = 1.45899901
Epoch: 346 cost = 1.45895820
Epoch: 347 cost = 1.45905676
Epoch: 348 cost = 1.45896258
Epoch: 349 cost = 1.45912013
Epoch: 350 cost = 1.45944533
Epoch: 351 cost = 1.45930305
Epoch: 352 cost = 1.45915141
Epoch: 353 cost = 1.45907750
Epoch: 354 cos

Epoch: 641 cost = 1.45863872
Epoch: 642 cost = 1.45872784
Epoch: 643 cost = 1.45877109
Epoch: 644 cost = 1.45872245
Epoch: 645 cost = 1.45868979
Epoch: 646 cost = 1.45865350
Epoch: 647 cost = 1.45867796
Epoch: 648 cost = 1.45878687
Epoch: 649 cost = 1.45865221
Epoch: 650 cost = 1.45852752
Epoch: 651 cost = 1.45859494
Epoch: 652 cost = 1.45859890
Epoch: 653 cost = 1.45856180
Epoch: 654 cost = 1.45855622
Epoch: 655 cost = 1.45857520
Epoch: 656 cost = 1.45891652
Epoch: 657 cost = 1.45883431
Epoch: 658 cost = 1.45884881
Epoch: 659 cost = 1.45867290
Epoch: 660 cost = 1.45857997
Epoch: 661 cost = 1.45867691
Epoch: 662 cost = 1.45872545
Epoch: 663 cost = 1.45858603
Epoch: 664 cost = 1.45860653
Epoch: 665 cost = 1.45853496
Epoch: 666 cost = 1.45853548
Epoch: 667 cost = 1.45861764
Epoch: 668 cost = 1.45866427
Epoch: 669 cost = 1.45876355
Epoch: 670 cost = 1.45860548
Epoch: 671 cost = 1.45884705
Epoch: 672 cost = 1.45871410
Epoch: 673 cost = 1.45862160
Epoch: 674 cost = 1.45860910
Epoch: 675 cos

Epoch: 973 cost = 1.45859013
Epoch: 974 cost = 1.45858607
Epoch: 975 cost = 1.45852718
Epoch: 976 cost = 1.45855861
Epoch: 977 cost = 1.45851192
Epoch: 978 cost = 1.45851512
Epoch: 979 cost = 1.45857768
Epoch: 980 cost = 1.45861912
Epoch: 981 cost = 1.45853391
Epoch: 982 cost = 1.45863705
Epoch: 983 cost = 1.45856280
Epoch: 984 cost = 1.45856385
Epoch: 985 cost = 1.45855179
Epoch: 986 cost = 1.45856667
Epoch: 987 cost = 1.45858288
Epoch: 988 cost = 1.45848060
Epoch: 989 cost = 1.45853772
Epoch: 990 cost = 1.45853205
Epoch: 991 cost = 1.45865102
Epoch: 992 cost = 1.45861573
Epoch: 993 cost = 1.45854158
Epoch: 994 cost = 1.45852313
Epoch: 995 cost = 1.45855374
Epoch: 996 cost = 1.45852065
Epoch: 997 cost = 1.45848117
Epoch: 998 cost = 1.45863080
Epoch: 999 cost = 1.45850229
Epoch: 1000 cost = 1.45850873


In [72]:
# on 1000 epoch
print(sess.run(accuracy, feed_dict={X: X_test, Y: y_test}))

0.60365856
